### ISSUE TITLE
Error: unsupported operand types

### ISSUE THREAD

**Issue by mgrimace** [Smart123s/ItchClaim#12]
Using docker implementation, I get the following error upon starting the container:
```bash
Traceback (most recent call last):
  File "itchclaim.py", line 3, in <module>
    from ItchClaim.__main__ import main
  File "/app/ItchClaim/__main__.py", line 27, in <module>
    from .web import generate_web
  File "/app/ItchClaim/web.py", line 30, in <module>
    from .ItchGame import ItchGame
  File "/app/ItchClaim/ItchGame.py", line 32, in <module>
    class ItchGame:
  File "/app/ItchClaim/ItchGame.py", line 178, in ItchGame
    def claimable(self) -> bool|None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

For reference, I am using docker compose:
```yaml
services:
  itchclaim:
    container_name: itch
    image: ghcr.io/smart123s/itchclaim
    volumes:
      - /root/docker/appdata/itch:/data
    command: [
      "--login", "${USERNAME}",
      "--password", "${PASSWORD}",
      "claim"
    ]
```

**Comment by Smart123s** [comment]
Fixed in https://github.com/Smart123s/ItchClaim/commit/706fd967a6b86837f981fc9b7abd88365811f5ed
